### ISSUE TITLE
Siri Commands

### ISSUE THREAD

**Issue by farberm** [bryanbartow/homebridge-alarm.com#1]
I have installed things but have two questions. 

I labeled the name as House Alarm but in app it just shows up as 'Alarm"

I am not sure this is why I also am having problems with Siri changing the state of the alarm from Away to Night to Disarm to Home

What commands are being used/understood by Siri

**Comment by farberm** [comment]
OK I changed the name to "Security Panel" to make sure the word Alarm did not conflict with the App Alarm. But still connot get Siri to do Away, Night, Disarm or Home command?

**Comment by lorddaren** [comment]
I tried several voice commands and no dice. I did find if I said "Security system arm stay" it would come up with a response of "No burglar alarm system found." I checked in my Insteon+ app and it isn't showing registered as a Security system. I wonder if there is some more configuration with home bridge that needs to be done.

**Comment by dhut1832** [comment]
I am having the same issue as well with trying to change the alarm state with Siri. I also have it set to arm stay in the "Good night" scene. Siri will arm the alarm to stay, but always says she has trouble with the device.

**Comment by bryanbartow** [comment]
I apologize for just now getting to this. Somehow, my Github notifications were turned off :( I've never been able to find any concrete commands for Siri to directly manipulate the security system. I had to setup up scenes, like @dhut1832 did, to get anything to work. That said, I have a "Good Morning" scene which disarms the system, a "Good Night" scene which sets it to Armed - Stay and an "I'm Leaving" scene which sets it to Armed - Away. All of them work fine.

The only issue I've had is that sometimes the Alarm.com site is slow to respond, so Siri will tell me she can't communicate with all of my devices. A few seconds later, however, the alarm will finally be set.

**Comment by thoppa** [comment]
I can't seem to get this to work at all.  When I try to change the state, either through siri or another app like iDevices, I get the "can't find the state" error.  I've tried using scenes as well to no avail.

**Comment by bryanbartow** [comment]
@thoppa Did you check the alarm.com site to see if there are any "nag" screens, as mentioned in the readme?

**Comment by thoppa** [comment]
Yes.  I double checked that.

**Comment by bryanbartow** [comment]
@thoppa The plugin is trying to find elements on the page with ids of ctl00_phBody_ArmingStateWidget_btnDisarm, ctl00_phBody_ArmingStateWidget_btnArmStay or ctl00_phBody_ArmingStateWidget_btnArmAway. If you login to alarm.com on your browser, can you find those elements in the page source?

**Comment by thoppa** [comment]
Yes.  Hmmm.  Maybe that phantomjs install didn't complete properly after all.  Unless you have a different idea, I'm going to investigate on that front.

**Comment by bryanbartow** [comment]
@thoppa I can't think of any other reason it would fail to find those elements. Either that or we're using different versions of phantom and the API changed between versions.

**Comment by bmartin5692** [comment]
Having the same issue as @thoppa on my setup. I am using Rpi2 and followed the link provided by @thoppa in #2 to install Phantomjs on Rpi. I've verified no nags and I can see the elements on the alarm.com site, but get the same errors when attempting a state change. 

Phantomjs -v shows 1.9.8.

> Logged in to alarm.com
> attempting to set state::2
> Can't find state element
> [Security panel] { message: 'Can\'t find the state element', success: false }

**Comment by bryanbartow** [comment]
I'm having intermittent issues with this as well, although sometimes it's working. I can only guess that the alarm.com site is being slow to respond and my plugin is timing out before the DOM is rendered. I could try increasing the timeout, but I think HomeKit / Siri have their own internal timeout, which will cause the device to report a failure.

**Comment by bryanbartow** [comment]
@Danimal4326 gave me a great idea with #3. I switched the plugin to point to the "mobile" version of Alarm.com's site and it works **much** faster. Try it out and let me know what you think.

**Comment by bmartin5692** [comment]
It is much faster and working great now.

**Comment by dhut1832** [comment]
Just tested and worked a lot faster for me. Thanks!

**Comment by nmcdan75** [comment]
Great addition for homebridge! Though I am thinking of switching to Xfinity Home.

It's working as long as I incorporate the command into a scene. 

**What commands are being directly understood by Siri as of right now?**

I have MyQ setup through Alarm.com. If I want to connect MyQ to homebridge, I have to disconnect it from Alarm.com :-/.

**Comment by bryanbartow** [comment]
@nmcdan75 The commands I've been able to setup and successfully use are:
- Good night
- Good morning
- I'm leaving
- I'm home

Of course, there may be others. I've never seen an "official" list.

**Comment by nmcdan75** [comment]
Thanks @bryanbartow  - I jumped on the Alarm.com bandwagon six years ago. I think I may have been a little too hasty to be an early adopter.

**Comment by bryanbartow** [comment]
@nmcdan75 Were you able to use any or all of those commands?

**Comment by nmcdan75** [comment]
@bryanbartow Thank you, yes I was. I am at the point of using Alarm.com just for an alarm and a garage door monitor. Appreciate your work!

**Comment by bryanbartow** [comment]
@nmcdan75 No problem. If no one else has any suggestions, I'll close this later today.

**Comment by thoppa** [comment]
Hmmm.  I updated to use the mobile version of the website.  BUT, this website gives me permanent nag-type pop-up.  "Welcome to the new Home screen view!...."  So, the plugin crashes.  I'm hoping that after a few more days they will decide the home screen view isn't all that "new."

**Comment by bryanbartow** [comment]
@thoppa That's interesting. I was never shown that screen and I used logged in to the mobile site for the first time a few days ago.

**Comment by farberm** [comment]
Where do I change things to the mobile website an what is the website address?

**Comment by bryanbartow** [comment]
@farberm You update to the latest version. It's pointing to the mobile site.

**Comment by ghost** [comment]
Was a server api key used or client api key utilized. If the client pi key was utilized, what domain was utilized.

**Comment by bryanbartow** [comment]
@jeremysmith214 Server API key. No domain necessary.

**Comment by jeremysmith214** [comment]
Thanks a ton. 

Im still having the following issue when accessories are initializing for alarmdotcom

[Error: You did not specify {'token'} or {'clinetID', "clientSecret', 'code'}, one set of which is required for the new API]

**Comment by bryanbartow** [comment]
I'm going to close this as no conversation has taken place in a good while.
