### ISSUE TITLE
Door Locks

### ISSUE THREAD

**Issue by yungsters** [bryanbartow/homebridge-alarm.com#10]
Alarm.com supports integration with various third party home automation accessories like door locks. Would you be opposed to converting this plugin to install as a platform instead of as a single accessory?

As a platform, this plugin would be able to provide the security panel as one accessory and any door locks as additional accessories. I've already confirmed that the mobile version of their site supports both door locks.

**Comment by bryanbartow** [comment]
Not opposed to it at all, although I don't have any devices to test with. I'll need to read up on the platform docs for Homebridge to see what's different for those plugins vs the accessory plugins. Of course, if someone wants to submit a PR, I'm all ears :)

**Comment by ghost** [comment]
Count me in to test this. Thanks gentlemen

**Comment by bryanbartow** [comment]
@jeremysmith214 Test away...

**Comment by ghost** [comment]
Questions about the locks. Do I configure the locks in my config file. Thanks Gentlemen

**Comment by yungsters** [comment]
You shouldn't need to. The plugin searches your account for any locks when Homebridge starts up.

**Comment by ghost** [comment]
For some reason its not finding any locks.

**Comment by ghost** [comment]
The error I have is the following:

Error while getting lock devices: TypeError: Cannot read property 'map' of undefined
