### ISSUE TITLE
Plugin crashes when user doesn't have locks

### ISSUE THREAD

**Issue by bryanbartow** [bryanbartow/homebridge-alarm.com#16]
The plugin gives the following error on Homebridge startup if the user does not have locks associated with him/her account:

`Error while registering accessories: TypeError: Cannot read property 'map' of undefined`

This causes the plugin to crash and, therefore, the security panel does not get registered nor does it show up in HomeKit control app(s).

**Comment by yungsters** [comment]
@bryanbartow When you go to `https://www.alarm.com/pda/{{sessionUrl}}/Locks.aspx`, what do you see?

**Comment by bryanbartow** [comment]
@yungsters Get an error message at the top of the page which reads: "You don't have permission to access the requested page." Screen shot at http://cl.ly/fm44

**Comment by yungsters** [comment]
Thanks for debugging and the feedback. Sorry for breaking!

**Comment by yungsters** [comment]
This should be all fixed now.
