### ISSUE TITLE
Doesnt install on Debian / RaspberryPi

### ISSUE THREAD

**Issue by amitgandhinz** [bryanbartow/homebridge-alarm.com#2]
Looks like there are issues installing this on a Raspberry Pi (linux/arm) running Jessie.

Has anyone else got this running on a Pi?

PhantomJS not found on PATH
Unexpected platform or architecture: linux/arm
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
npm WARN install:phantomjs@1.9.19 phantomjs@1.9.19 install: `node install.js`
npm WARN install:phantomjs@1.9.19 Exit status 1
/usr/local/lib
└── (empty)

**Comment by bryanbartow** [comment]
I've only installed this on my Macs, so I don't have any experience on Linux. Having said that, it looks like your issue is definitely related to Phantom and/or NPM. As far as I can tell it's not related to the plugin itself. Hopefully someone else is able to help. I'll leave this open.

**Comment by thoppa** [comment]
I don't know why it doesn't work right, but the guide here helped me overcome this:
https://www.bitpi.co/2015/02/10/installing-phantomjs-on-the-raspberry-pi/

**Comment by bryanbartow** [comment]
@amitgandhinz Can you confirm this works?

**Comment by bmartin5692** [comment]
Can confirm the instructions @thoppa provided work on Raspberry Pi2 with Raspbian / Jessie.

**Comment by bryanbartow** [comment]
Looks like it's working. I'm going to close this.
