### ISSUE TITLE
Door lock APIs with no door locks

### ISSUE THREAD

**Issue by tagyoureit** [bryanbartow/homebridge-alarm.com#20]
Bryan,
I don't have any door locks through Frontpoint.  I did still enable the API requests through WrapAPI but am seeing the following in the log:
[5/5/2016, 9:13:05 PM] [Security Panel] Error while getting lock devices: TypeError: Cannot read property 'map' of undefined

I don't see this having any adverse effect, but could the API detect whether there are actually any door locks installed?  Or maybe put something in the config file to enable/disable the door lock APIs? (It threw a different error when I didn't have the door lock APIs enabled.)

thx!

**Comment by bryanbartow** [comment]
I'm going to defer to @yungsters on this one.

**Comment by ghost** [comment]
I have the same issues as well

**Comment by bryanbartow** [comment]
@tagyoureit I just published version 0.7.0, which implements conditional loading of the various device types. See the readme for more info.

**Comment by tagyoureit** [comment]
@bryanbartow Thanks!  Will have to try this out.  👍
