### ISSUE TITLE
Does not notify or log errors for logging in to ADC website

### ISSUE THREAD

**Issue by silverhack77** [bryanbartow/homebridge-alarm.com#22]
I had a typo in my config.json file where "username" was incorrect, and I couldn't figure out why this plugin wasn't working.   Eventually I saw the typo and fixed it.  It would have been helpful if the debug output had some info with the error when logging in to the alarm.com website.

**Comment by bryanbartow** [comment]
@silverhack77 Not a bad idea.

**Comment by bryanbartow** [comment]
@silverhack77 I just published version 0.7.2, which now logs login errors on alarm.com. You'll also need to update the login call on WrapAPI.
