### ISSUE TITLE
Arm Stay With No Entry Delay

### ISSUE THREAD

**Issue by ethansimpson** [bryanbartow/homebridge-alarm.com#24]
I noticed in the Elgato Eve app that my security panel has four arming options: Stay, Away, Disarm, and Night. Is it possible to setup the Night Arm option to arm the panel stay with no entry delay? Right now it appears to do the same thing as the stay option.

**Comment by rcaslis** [comment]
Short answer: no

Since this plugin uses the mobile alarm.com site behind the scenes, the plugin is limited to the functions on the mobile alarm.com site.  That site doesn't expose any options for arm away, arm stay, or disarm.

**Comment by ethansimpson** [comment]
Got it, I didn't realize the mobile site didn't have that option since their apps did. Thanks.

On Jun 23, 2016, at 3:18 AM, rcaslis notifications@github.com wrote:

Short answer: no

Since this plugin uses the mobile alarm.com site behind the scenes, the plugin is limited to the functions on the mobile alarm.com site. That site doesn't expose any options for arm away, arm stay, or disarm.

**Comment by bryanbartow** [comment]
@ethansimpson @rcaslis Pretty much sums it up. Can't do it unless the mobile site supports it.
