### ISSUE TITLE
Garage Door Integration

### ISSUE THREAD

**Issue by rmervine** [bryanbartow/homebridge-alarm.com#26]
Hello,

I have garage door integration with alarm.com. Is it possible that this could be added in? I think I tried the PDA login and I don't see garage doors listed there. So wasn't sure if this was possible.

**Comment by rcaslis** [comment]
If there isn't a way to control the garage door from the mobile alarm.com site (m.alarm.com), then this plugin won't be able to control it.  This plugin uses the mobile site to issue commands to alarm.com.

I don't have an integrated garage door so I can't check myself.

**Comment by bryanbartow** [comment]
Pretty much what @rcaslis said.
