### ISSUE TITLE
Thermostats

### ISSUE THREAD

**Issue by blalwani** [bryanbartow/homebridge-alarm.com#30]
Any planned support for thermostats?

**Comment by bryanbartow** [comment]
@blalwani Does alarm.com support thermostats? If so, I don't have one to test with. Feel free to implement it and submit a PR.

**Comment by bryanbartow** [comment]
@blalwani or anyone else know the answer to this?

**Comment by jdshkolnik** [comment]
Alarm.com does seem to [support thermostats](https://www.alarm.com/solutions/energy.aspx) but I don't use them. Neither the original poster, nor anyone else, seem particularly interested in pursuing this so I'll close for now.
