### ISSUE TITLE
Home.App iOS Questions

### ISSUE THREAD

**Issue by jpstephens** [bryanbartow/homebridge-alarm.com#35]
When I go to arm the security system in Home.App on iOS I am presented with the following options:

- Home
- Away
- Night
- Off

What do all of these mean?  What is the difference between each of them?

**Comment by bryanbartow** [comment]
@jpstephens These are the preset modes that Home app supports. However, alarm.com only supports Disarm, Arm Away and Arm Stay. I'm assuming you're already familiar with these as you presumably have a system. The question, then, is how do the two map to each other? 

- Home and Off in Home app both call Disarm on alarm.com. 
- Away in Home app calls Arm Away on alarm.com
- Night in Home app calls Arm Stay on alarm.com

**Comment by jpstephens** [comment]
Thanks, is there a way to hide the duplicate function of "home" / "off"?

**Comment by bryanbartow** [comment]
@jpstephens That's a Home app issue, but, as far as I know, the answer to that question is no.
