### ISSUE TITLE
Alarm.com redesign

### ISSUE THREAD

**Issue by shane-glint** [bryanbartow/homebridge-alarm.com#37]
Looks like a redesign of alarm.com landing page is messing up some of the integrations. I logged in to make sure I am not seeing a nagging screen and the whole site looks different. The specific error I am getting in homebridge is: Request `<username>/alarmdotcom/login/0.1.0` was unsuccessful:
 - None of the output scenarios matched. See the raw data received in rawData

**Comment by miked2318** [comment]
Same here. Just noticed it now when invoking my "good night" scene.

**Comment by kpdillon** [comment]
Same here, mine is broken.

**Comment by shane-glint** [comment]
I did a tiny bit of research and looks like the API call on APIWrap uses CSS to check that the elements are there it needs. My guess is the CSS no longer works with the redesign although I think everything needed from there is still available.

**Comment by kpdillon** [comment]
Mine is working again!  Not sure if alarm.com rolled something back?

**Comment by shane-glint** [comment]
Looks like alarm.com redesign is still there but agree it is working now. WrapAPI didn't change but it is no longer throwing up so maybe they changed their CSS. Either way closing this for now!
