### ISSUE TITLE
Allow more options when automating Security System accessory

### ISSUE THREAD

**Issue by danemacmillan** [bryanbartow/homebridge-alarm.com#39]
Creating an automation for the Security System accessory exposes three options:
- Triggers
- Disarms
- Arms

![img_5242](https://cloud.githubusercontent.com/assets/4390491/22117199/0f79b4a6-de41-11e6-96a0-8d74f77c71e7.PNG)

There should be two additional options provided, to correspond with the Alarm.com API:
- Arms (stay)
- Arms (away)

They should be added because the Alarm.com API provides this nuance for arming an alarm system. It's common to most alarm systems, really. "Arms (stay)" means that the perimeter of the system is armed, but motion sensors are not; this is common for people who are staying home to sleep, for example, and want the perimeter sensors armed, but do not want to trigger the motion sensors in the middle of night if they walk around or inevitably move in bed. "Arms (away)" means that all sensors are armed.

Exposing this nuance in Home's automation section means that a user can create an automation for turning off all the lights when "Arms (away)" is selected. Currently, selecting "Arms" handles both the "stay" and "away" situations. That makes creating such an automation ineffective, as users who are arming with "stay" probably do not want to turn all the lights off, while users arming with "away" almost certainly do.

Can these provided options be modified, or are they up to Apple's team developing `HomeKit` and the `Home` app for the Security System accessory?

**Comment by bryanbartow** [comment]
You'll notice that this plugin and the Home app support both Armed states. In the Home app, viewing the device will give you options to set Away (Armed Away) and Night (Armed Stay) states.

![Home app](https://cl.ly/ipkw/IMG_0051.PNG)

The issue you're describing is with the automation capabilities of Home and/or HomeKit.

**Comment by danemacmillan** [comment]
> The issue you're describing is with the automation capabilities of Home and/or HomeKit.

I know. That's the issue I described. That's why I opened the ticket. I have no issue setting those nuanced states outside of creating an automation. I notice you marked this ticket closed but also "not possible yet." We'll have to wait and see what Apple exposes in future updates :+1:

**Comment by bryanbartow** [comment]
@danemacmillan With all due respect, open a ticket with Apple. This is not an issue with my plugin. It works as intended.

**Comment by danemacmillan** [comment]
@danemacmillan
> Can these provided options be modified, or are they up to Apple's team developing HomeKit and the Home app for the Security System accessory?

@bryanbartow 
> The issue you're describing is with the automation capabilities of Home and/or HomeKit.

Yes, that's exactly how I described it--as likely on their end. My ticket wanted confirmation on this very point. You misread. I was not blaming your code for Apple's shortcomings. I was looking to confirm my suspicion that it is likely on their end and therefore their responsibility.

@danemacmillan
> We'll have to wait and see what Apple exposes in future updates.

@bryanbartow 
> This is not an issue with my plugin.

Yes, we both agree.

Anyway, I like your plugin.

**Comment by bryanbartow** [comment]
Thanks. If Apple ever supports this, I'll re-open the ticket and consider it a feature request.
