### ISSUE TITLE
A Suggestion

### ISSUE THREAD

**Issue by solomonj1963** [bryanbartow/homebridge-alarm.com#43]
I have been going back to 0.4.1 version because I get name conflicts in homebridge since my lights and locks are on my Razberry as primary zwave controller with ADC as secondary.  I'm more than willing to do that, but then realize this might be an enhancement for you to consider, as others might benefit.  

My thought is to add some additional parameters to the config.json to enable or disable a class of device.  For example, see last 3 lines in sample idea below.  Don't feel obligated, but this could prove simple and useful for anyone running ADC controller as secondary.  I've found that responsiveness of devices is blazing fast compared to through ADC apps, plus I've been able to add devices that ADC doesn't support.  I'd offer to contribute if I knew how to code well!  

Configuration sample:

{
  "platforms": [
    {
        "platform": "Alarmdotcom",
        "name": "Security Panel",
        "username": "test@example.com",
        "password": "testpassword",
        "apiKey": "wrapapikeygoeshere",
        "apiUsername": "wrapapiusername",
        "enablePanel": true,
        "enableLocks": false,
        "enableLights": false 
    }
  ]
}

**Comment by bryanbartow** [comment]
This is directly related to #20. I can look at doing something here.

**Comment by bryanbartow** [comment]
@solomonj1963 I just published version 0.7.0, which implements conditional loading of the various device types. I used a slightly different syntax. See the readme for more info.

**Comment by solomonj1963** [comment]
Wow!  Amazing!!!!  Thank you SO SO much!!!!

**Comment by bryanbartow** [comment]
@solomonj1963 No problem. I got your 🎁. Thank you very much. It certainly wasn't necessary.

**Comment by solomonj1963** [comment]
Maybe it wasn't necessary, but well deserved...
