### ISSUE TITLE
Missing alarmdotcom/getviewstate bookmark in npm instructions

### ISSUE THREAD

**Issue by jdshkolnik** [bryanbartow/homebridge-alarm.com#44]
Hi,

I just installed and was getting an error until I realized the [npm instructions](https://www.npmjs.com/package/homebridge-alarmdotcom) were missing a bookmark for [getViewState](https://wrapapi.com/#/view/bryanbartow/alarmdotcom/getviewstate/latest?_k=6nrkw8).

**Comment by bryanbartow** [comment]
@jdshkolnik Good catch. I'll update when I'm back in front of my machine.

**Comment by bryanbartow** [comment]
Updated.
