### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by mikegyverCT** [bryanbartow/homebridge-alarm.com#45]
Hi,

Hoping someone can help me with some basic install issues.

I have followed each step on this page:
https://www.npmjs.com/package/homebridge-alarmdotcom
including this:
https://www.npmjs.com/package/homebridge-alarmdotcom/tutorial

other then some install permissions, it seems to have installed fine after these:
npm install -g homebridge
npm install -g homebridge-alarmdotcom
no errors reported.

the part that is confusing to me is where to I put config.json file.
it says it has to be ~/.homebridge/config.json

without it, it does not complain, nor any error messages.  I then tried to create a .homebridge folder, but found it odd to have to manually create it.

Is this folder supposed to be automatically installed or do I have to create it?

Then inside the config.json file do I just put (with my variables of course), should there be more?:
{
  "platforms": [
    {
        "platform": "Alarmdotcom",
        "name": "Security Panel",
        "username": "test@example.com",
        "password": "testpassword",
        "apiKey": "wrapapikeygoeshere",
        "apiUsername": "wrapapiusername"
    }
  ]
}

thanks in advance.

**Comment by bryanbartow** [comment]
@mikegyverCT This seems like a homebridge issue. You may want to [create an issue there](https://github.com/nfarina/homebridge). The .homebridge folder should automatically be created in your home folder upon installation. Again, you should check [over there](https://github.com/nfarina/homebridge) for help.
