### ISSUE TITLE
Issue - Request `wrapapiuserid/alarmdotcom/initlogin/0.0.4` was unsuccessful:  - There was an unexpected error

### ISSUE THREAD

**Issue by nlakamsany** [bryanbartow/homebridge-alarm.com#50]
Hi,

Thank you for doing this awesome work.
This is my first accessory I am adding in homebridge. I am getting the following error when I click on the security panel accessory in home app. It shows 'no response'. When I click on it, I get the following error in terminal. I am running this raspberry pi3.
[Security Panel] Request `wrapapiuserid/alarmdotcom/initlogin/0.0.4` was unsuccessful:
 - There was an unexpected error

I have used server api key. Below is the config:

`{
"bridge": {
"name": "Homebridge",
"username": "mac",
"port": 51826,
"pin": "031-45-154"
},
"platforms": [{
"platform":"Alarmdotcom",
"name":"Security Panel",
"username":"x@gmail.com",
"password":"alarm.com password",
"apiKey":"KoWOvbHIqP5rKzcVpblvwPht1mMoyua4",
"apiUsername": "wrapapiuserid",
"accessories":{
"panel":  true,
"lights":false,
"locks": false
}
}]
}`

**Comment by bryanbartow** [comment]
@nlakamsany I noticed you created and closed this in close succession. Did you figure it out?

**Comment by nlakamsany** [comment]
Yes Bryan. Thanks a lot! I did not bookmark earlier. Appreciate the great work and effort.
