### ISSUE TITLE
TypeError Message loading Homebridge

### ISSUE THREAD

**Issue by rbiffle** [bryanbartow/homebridge-alarm.com#53]
I get a TypeError message when loading homebridge.  It says "Cannot read property "indexOf" of undefined at API.platform...  I followed the Readme instructions.  Signed up for wrapapi account.  As for the bookmarking, I clicked each link you listed in WrapAPI Calls section and when the website opened i selected bookmark, i did not touch any of the fields, is that correct?  After that, i generated a new API key.  As for the config file, i have a panel, but no lights and locks so I changed those to false.  My appologies if this is something minor, this is my first raspberry pi and my first time with homebridge.  There's more to the error message if that might help you assist me.  I attached a photo of the error message.
![img_1980](https://cloud.githubusercontent.com/assets/23202815/24861303/ec90c670-1dbd-11e7-8fdc-e828812e1b16.JPG)

**Comment by bryanbartow** [comment]
Looks like a homebridge error to me. Might want to check [their issues](https://github.com/nfarina/homebridge/issues) for possible solutions. Closing for now. Let me know if you are fairly certain this is an issue with my plugin.

**Comment by rbiffle** [comment]
You can close it.  Thanks.
