### ISSUE TITLE
No Response

### ISSUE THREAD

**Issue by kpdillon** [bryanbartow/homebridge-alarm.com#55]
Did something change with alarm.com?  I am getting a No Response output message from HomeBridge.

**Comment by djstarr** [comment]
Seeing the same thing.

**Comment by avavricek** [comment]
It looks like my wrapAPI calls were all deleted.

**Comment by avavricek** [comment]
"Request `avavricek/alarmdotcom/initlogin/0.0.4` was unsuccessful: - There was an unexpected error" possibly a change with wrapapi?

**Comment by davidvanvo** [comment]
I took a look at all of the wrapapi on my end and noticed one was marked "incomplete".

https://wrapapi.com/#/view/andrewmattie/alarmdotcom/locks/latest

**Comment by bryanbartow** [comment]
See #56. As of 48 hours ago, I no longer have an alarm.com system. I'll need someone to take this over. In the meantime, if someone fixes and submits a PR, I'll be happy to merge it.

**Comment by djstarr** [comment]
Also noting that the wrapapi calls don't seem to be working straight from the site; that's seemingly where the troubleshooting should start. But honestly the wrapapi UI is hurting my brain. A great tool, but not entirely sure where to start.

edit: Apparently working again. Perhaps this was just a wrapapi burp?

**Comment by kpdillon** [comment]
It seems to be working again for me as well.

**Comment by bryanbartow** [comment]
I can confirm this was a WrapAPI issue as I use it for another project.
