### ISSUE TITLE
Don't let this plugin die. Take it over!

### ISSUE THREAD

**Issue by bryanbartow** [bryanbartow/homebridge-alarm.com#56]
I just moved into a new home. We will no longer be using an alarm.com system, which means I won't really be able (or need) to work on this plugin anymore. Is there anyone who might be able to take over ownership? I'd hate to see it die as I know there are quite a few active users.

**Comment by jdshkolnik** [comment]
Hi Bryan,

I don't want to see it die. If no other choice, I'd be willing to at least stay active enough to manage the repo although I can't commit to fixing all problems.

**Comment by bryanbartow** [comment]
@jdshkolnik So far, you're the only person to respond, so anything would be better than nothing.

**Comment by jdshkolnik** [comment]
Does it have to be a transfer? You deserve all the credit here and you might one day get a benefit from it. Why not just add me as a collaborator?

**Comment by bryanbartow** [comment]
@jdshkolnik That's certainly an option, too. I just didn't want anyone feeling like they needed to involve or defer to me on future direction, etc. I'll add you.

**Comment by jdshkolnik** [comment]
@bryanbartow I'm closing this but can obviously reopen if you'd like to keep looking for more collaborators.
