### ISSUE TITLE
Alarm.com garage door integration

### ISSUE THREAD

**Issue by joewilliamsca** [bryanbartow/homebridge-alarm.com#58]
Hey guys,

Enjoy the plugin, and it works great for me.    I do have a garage door hooked up to Alarm.com,  and I would like to integrate it.   Would you be willing to let me implement the feature request?

**Comment by jdshkolnik** [comment]
Go for it.

**Comment by joewilliamsca** [comment]
Sounds good.   Thanks :)

**Comment by joewilliamsca** [comment]
Hey guys,  so I have dug into the alarm.com garage door integration.   After further looking into the "pda" app which the plugin is using through wrapAPI,  there is no access to the garage door open/close setting, or a stable 'state' of the garage door,  so I am thinking that the garage door integration is an afterthought of the 'pda' app that is being hosted by alarm.com

So here are the options.

1) make a recording of the web app through wrapAPI,  but the issue is that its a rich UI,  and if it changes,  then it alarm.com makes a change to the app,  it could easily break the selenium style recording in wrapAPI  (where the 'pda' app is pretty much text based and hyperlinks)  I would also expect the playback will also be very slow, so its not going to be quick to respond,  due to multiple calls to drive the UI

2) Could do a fiddler/wireshark recording of the web app to see if its calling API's inside of alarm.com, and seeing if there is an API that can be extracted for the garage door.

I think Im going to have a look at the repository that @jhurliman developed to work with front point, to see if it gets me a little further with my garage door on alarm.com, but I am an ADT customer  (not front point) but I will check it out anyways.   I have a feeling at the end of the day,  I will end up moving my garage door back over to the MyQ app,  and using the homebridge-myq plugin for the integration back to home kit,  since the automation around the garage door is very limited,  and continue to use this plugin for alarm.com for my alarm and z-wave lights (which works really well for me)

**Comment by joewilliamsca** [comment]
since the automation in alarm.com for the garage door is very limited...   (thats what I was meant to say in my above comment)

**Comment by joewilliamsca** [comment]
Just closing this ticket,  since I’m not pursuing the garage door integration
