### ISSUE TITLE
Dealer

### ISSUE THREAD

**Issue by NeTechcom** [bryanbartow/homebridge-alarm.com#59]
I added a nutone light switch nws15z & it works fine on the iq panel 2 but it doesn't show up on alarm.com. any reasons why?

**Comment by joewilliamsca** [comment]
Hi NeTechcom - when you say it doesn’t show up in alarm.com,  you are not able to control the switch from alarm.com,  or can you control the device from alarm.com’s site but not able to see the switch from this plugin’?

**Comment by NeTechcom** [comment]
Hi I figured out the problem already.
 I was able to control it from my iq panel 2 but not online at all.

The problem was that I haven't had selected the "lights" option on my
alarm.com plan,  as soon that i added it (For $1.25) it came up on the app
And online thanx

**Comment by joewilliamsca** [comment]
Glad to hear you got the problem worked out.   Have a great day :)
