### ISSUE TITLE
Support Silent Arming

### ISSUE THREAD

**Issue by omarshahine** [bryanbartow/homebridge-alarm.com#6]
By default when I arm stay, I wish for that to be done "silently". This is so that the alarm does not do the beeping countdown. This is an option on the alarm.com mobile app. 

In the web there is a checkbox "Silent Arming" that can be set. Any idea if this can be done from the plugin?

**Comment by bryanbartow** [comment]
@omarshahine I apologize it took so long for me to reply. I somehow missed this. It should be doable - most likely as an option in the config file. I haven't had much time to dedicate to this project lately. Do you want to submit a pull request?

**Comment by bryanbartow** [comment]
@omarshahine Actually, I take that back. The mobile site, which we've switched to a while back, does not support the silent arming or no entry delay options. You're welcome to fork this and go back to the "full" site to do so.

**Comment by bryanbartow** [comment]
Closing since we no longer use the standard version of the site.
