### ISSUE TITLE
wrapapi links fail

### ISSUE THREAD

**Issue by jnanes** [bryanbartow/homebridge-alarm.com#60]
all links fail, is this project dead?

**Comment by joewilliamsca** [comment]
Hi jnanes,  the project is not dead.   I have a lot of automation around this plugin,  and it works for me.  When you say all links fail,  can you provide us a description of what the errors are?

**Comment by jnanes** [comment]
I get a failure that the wrapapi.com links are bad and no longer exist . Maybe I am reading the tutorial wrong ?

Thanks,

Jesse Nanes

**Comment by jnanes** [comment]
more specifically - We could not find the page you were looking for. Please double-check the link you followed.

**Comment by jnanes** [comment]
so i found the api's by searching the wrapapi.com site and bookmarked them. i have my json configured but the alarm panel is not showing up in homekit. can anyone help me find what im missing?


[2018-1-14 15:16:14] [alarm] Initializing Alarmdotcom platform...
[2018-1-14 15:16:14] Loading 1 accessories...
[2018-1-14 15:16:14] [Roomba] Initializing Roomba690 accessory...
[2018-1-14 15:16:14] [Roomba] Initialised Roomba with Name: [Roomba] Hostname: [10.5.5.6] BLID: [3162880890518770] Model: [690]
[2018-1-14 15:16:14] [Roomba] Services requested
[2018-1-14 15:16:14] [Roomba] Reporting that we support AccessoryInformation, SwitchService and BatteryService
[2018-1-14 15:16:14] [Config] Console is listening on port 8080.
Setup Payload:
X-HM://00253CFM24DMJ

**Comment by mkormendy** [comment]
* [initlogin](https://wrapapi.com/api/bryanbartow/alarmdotcom/initlogin/latest) - https://wrapapi.com/api/bryanbartow/alarmdotcom/initlogin/latest
* [login](https://wrapapi.com/api/bryanbartow/alarmdotcom/login/latest) - https://wrapapi.com/api/bryanbartow/alarmdotcom/login/latest
* [getviewstate](https://wrapapi.com/api/bryanbartow/alarmdotcom/getviewstate/latest) - https://wrapapi.com/api/bryanbartow/alarmdotcom/getviewstate/latest
* [disarm](https://wrapapi.com/api/bryanbartow/alarmdotcom/disarm/latest) - https://wrapapi.com/api/bryanbartow/alarmdotcom/disarm/latest
* [armstay](https://wrapapi.com/api/bryanbartow/alarmdotcom/armstay/latest) - https://wrapapi.com/api/bryanbartow/alarmdotcom/armstay/latest
* [armaway](https://wrapapi.com/api/bryanbartow/alarmdotcom/armaway/latest) - https://wrapapi.com/api/bryanbartow/alarmdotcom/armaway/latest
* [locks](https://wrapapi.com/api/andrewmattie/alarmdotcom/locks/latest) - https://wrapapi.com/api/andrewmattie/alarmdotcom/locks/latest
* [lock](https://wrapapi.com/api/yungsters/alarmdotcom/lock/latest) - https://wrapapi.com/api/yungsters/alarmdotcom/lock/latest
* [unlock](https://wrapapi.com/api/yungsters/alarmdotcom/unlock/latest) - https://wrapapi.com/api/yungsters/alarmdotcom/unlock/latest
* [lights](https://wrapapi.com/api/rcaslis/alarmdotcom/lights/latest) - https://wrapapi.com/api/rcaslis/alarmdotcom/lights/latest
* [lighton](https://wrapapi.com/api/rcaslis/alarmdotcom/lighton/latest) - https://wrapapi.com/api/rcaslis/alarmdotcom/lighton/latest
* [lightoff](https://wrapapi.com/api/rcaslis/alarmdotcom/lightoff/latest) - https://wrapapi.com/api/rcaslis/alarmdotcom/lightoff/latest
