### ISSUE TITLE
Siri says my apologies "I can't control your home security system"

### ISSUE THREAD

**Issue by mkormendy** [bryanbartow/homebridge-alarm.com#63]
For some reason, I can't get Siri's commands to work with my security system.

Homekit and Homebridge, and the alarm.com setup is working perfectly when I go into the Homekit app interface and change the Security Panel status.

But when I ask Siri to do it, it says something along the lines of "I can't control your home security system".

**Comment by jdshkolnik** [comment]
What're you asking it to do and how? See [this article](http://www.idownloadblog.com/2018/02/09/homepod-smart-home-security-iphone-authentication/).

**Comment by mkormendy** [comment]
I simply ask Siri to “arm my security system”. I’m asking my phone .. it is unlocked with Face ID, so I know it’s not a phone authentication issue.

**Comment by mkormendy** [comment]
I’ve got a work around for the time being where I tell Siri, “Leaving home” or “Good night” or “Arriving home” and those phrases are tied to corresponding scenes. But it’s not perfect.

**Comment by jdshkolnik** [comment]
Would a scene like "Secure My Home" work?

**Comment by mkormendy** [comment]
> I’ve got a work around for the time being where I tell Siri, “Leaving home” or “Good night” or “Arriving home” and those phrases are tied to corresponding scenes. But it’s not perfect.

Suggested per Issue #1
