### ISSUE TITLE
Alarm System Not Updating

### ISSUE THREAD

**Issue by davidvanvo** [bryanbartow/homebridge-alarm.com#64]
Updating the Alarm though Home app has been unsuccessful. When arming, Home will update and show Armed, but the alarm itself never updates. After an updated poll the Home app reverts to the correct status and shows unarmed.

**Comment by jdshkolnik** [comment]
This works for me and others so we'd need more information to understand why it doesn't for you. Can we see your config?

**Comment by davidvanvo** [comment]
My configuration is standard. Obviously, I've commented out the actual data. Also, to clarify, this has been working fine for me for quite some time now. This just started happening the past couple of days. I've even gone as far as uninstalling/reinstalling homebridge and this plugin. I also tried logging into alarm.com through a mobile browser to confirm if there wasn't any alerts or dialogue on the website that could have caused any issues.

> {
      "platform": "Alarmdotcom",
      "name": "Central Security Group",
      "username": "xxxxxx",
      "password": "xxxxxx",
      "apiKey": "xxxxxx",
      "apiUsername": "xxxxxx",
      "accessories": {
        "panel": true,
        "lights": false,
        "locks": false
      }
    },

**Comment by jdshkolnik** [comment]
You wrote in original post that it "reverts to the correct status and shows unarmed". You said it happens "when arming" so wouldn't the correct status show armed?

**Comment by davidvanvo** [comment]
Here's the scenario:

1) House is UnArmed. In the Home app, I'll toggle to Arm and that Toggle status updates to Arm immediately.
2) Typically, the actual Control Panel would Arm within 5sec, but nothing happens here.
3) I'll return to the Home app, switch view and back to refresh and the Alarm status has now reverted back to UnArm.

I'll do this several times repeatedly. I'll even try the other way around where I'm Armed and toggle to UnArm on the Home app but no response on the Control Panel. 

1 out 10 attempts actually works.

**Comment by jdshkolnik** [comment]
How quickly do you see panel state change in the Home app if you set it via control panel?

**Comment by davidvanvo** [comment]
The Home App responds instantly when changed via Control Panel or the Official Alarm app.

**Comment by jdshkolnik** [comment]
It seems as if it might be a problem with one of your WrapAPI links.

**Comment by davidvanvo** [comment]
I re-bookmarked all of them but no luck.

**Comment by jdshkolnik** [comment]
It might be resolved whenever #32 is implemented.

**Comment by davidvanvo** [comment]
for now, this somehow corrected itself in the recent update.
