### ISSUE TITLE
WrapAPI Calls failing

### ISSUE THREAD

**Issue by dannycohn** [bryanbartow/homebridge-alarm.com#65]
This isn't an issue so much with the homebridge code, but I'm trying to use the WrapAPI calls that you set up in a separate app of mine. When I call the login endpoint, I get a sessionUrl, but then when I pass that, along with my username and password, to initlogin, just like your homebridge code does, I get an expired session error.  Any thoughts?

**Comment by jdshkolnik** [comment]
Is your code in a public repo we could compare against?

**Comment by dannycohn** [comment]
Unfortunately no. I found that the issue was intermittent. Combine that with the fact that there are delays when issuing commands from Alarm.com, and I decided to go a different route. This is for an openHab integration. I used a relay board connected to a keyfob to control the alarm.  I might revisit this at a later point to try to get real-time system status updates (I'm currently relying on email notifications that get parsed automatically). If I do, and I'm still experiencing problems, I'll post some code in a gist.
