### ISSUE TITLE
New to Pi and Homebridge

### ISSUE THREAD

**Issue by ghost** [bryanbartow/homebridge-alarm.com#8]
Greetings, 

I am new to this whole realm of exciting things so please be patient with my jargon. When my homebred is initialized, I run into the following issue.

[Error: You did not specify {'token'} or {'clinetID', "clientSecret', 'code'}, one set of which is required for the new API]

Also with APIkey do i select a server key or a client key.

If selecting client key do i simply use alarm.com for the host. Thanks

**Comment by bryanbartow** [comment]
@jeremysmith214 You need a server key. I originally missed that in the documentation, but have since updated it to reflect this. I'm not sure about the token error. I've never seen it, but it may have to do with the key issue. Please let me know if adding a server key fixes it or not.

**Comment by ghost** [comment]
I tried by adding the server key. With no luck. Im going to try some other things as well. If you have any ideas please shoot them over. Once again thanks

**Comment by bryanbartow** [comment]
@jeremysmith214 Can you post your config? Also, are you using the latest version (0.2.22)?

**Comment by ghost** [comment]
Yes I have the latest version

"accessories": [
        {
          "accessory": "Alarmdotcom",
          "name": "Security",
          "username": "jeremysmith214",
          "password": "************",
          "apiKey": "4Rq2BU6F14gDeiNTApRa5UpVqd82dV8k",
          "apiUsername": "jeremysmith214"
        }

**Comment by bryanbartow** [comment]
@jeremysmith214 You bookmarked or cloned my API calls, right? So, your endpoints look like https://wrapapi.com/use/jeremysmith214/alarmdotcom/armaway/0.0.2?

**Comment by bryanbartow** [comment]
@jeremysmith214 When you added the server key did you get the same error or a different error?

**Comment by ghost** [comment]
same error

**Comment by bryanbartow** [comment]
@jeremysmith214 What about my previous question? Does that endpoint match yours?

**Comment by ghost** [comment]
Thanks for everything @bryanbartow I deleted the old endpoints and bookmarked them again. Followed that procedure by asking for another server api key. I am up and running now. Not to be greedy but in the future will there possibly be an integration of the zwave lights switches from alarm.com within the homebridge setup. 

Once again huge thanks

**Comment by bryanbartow** [comment]
@jeremysmith214 Glad it's working and sorry for the confusion. I don't have zwave light switches in my setup, so someone else would have to work on that. If they do, and submit a PR I'll merge it in.
